-- 首页九宫格、攻略、排行（已有库执行一次）
CREATE TABLE IF NOT EXISTS home_cats (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  cat_code VARCHAR(32) NOT NULL UNIQUE,
  name VARCHAR(64) NOT NULL,
  icon VARCHAR(512) DEFAULT NULL,
  hero VARCHAR(512) DEFAULT NULL,
  page_type VARCHAR(32) NOT NULL,
  sort_order INT DEFAULT 0,
  status TINYINT DEFAULT 1
) ENGINE=InnoDB COMMENT='首页九宫格';

CREATE TABLE IF NOT EXISTS travel_guides (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  guide_code VARCHAR(32) NOT NULL UNIQUE,
  title VARCHAR(128) NOT NULL,
  photo VARCHAR(512) DEFAULT NULL,
  place VARCHAR(128) DEFAULT NULL,
  summary VARCHAR(256) DEFAULT NULL,
  body TEXT,
  sort_order INT DEFAULT 0,
  status TINYINT DEFAULT 1
) ENGINE=InnoDB COMMENT='出行攻略';
