-- 支付与会员字段增量（已有库执行一次）
ALTER TABLE members
  ADD COLUMN saved_fen INT DEFAULT 0 COMMENT '年卡累计抵扣分',
  ADD COLUMN trial_used TINYINT DEFAULT 0 COMMENT '是否已用7天试用';

ALTER TABLE orders
  ADD COLUMN title VARCHAR(128) DEFAULT NULL,
  ADD COLUMN cover VARCHAR(512) DEFAULT NULL,
  ADD COLUMN place VARCHAR(128) DEFAULT NULL,
  ADD COLUMN qty INT DEFAULT 1,
  ADD COLUMN visitor VARCHAR(64) DEFAULT NULL,
  ADD COLUMN phone VARCHAR(20) DEFAULT NULL,
  ADD COLUMN use_day DATE DEFAULT NULL,
  ADD COLUMN pay_amount INT DEFAULT 0 COMMENT '实付分',
  ADD COLUMN covered_by_card TINYINT DEFAULT 0 COMMENT '是否年卡抵扣';
